### ISSUE TITLE
No module named 'gmapslocsharing'

### ISSUE THREAD

**Issue by njf2125** [shr00mie/gmapslocsharing#3]
I'm trying to get this set up in my HA config, but am getting the below error in my HA log.  I've created the script for the Ubuntu install and run it (after editing my HA install path) so I'm not sure what's going on.  Probably something simple that I overlooked. Help?

```
2019-06-03 11:30:15 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform google_maps
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 177, in async_setup_platform
    disc_info)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 54, in setup_scanner
    scanner = GoogleMapsScanner(hass, config, see)
  File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 62, in __init__
    from gmapslocsharing import GoogleMaps
ModuleNotFoundError: No module named 'gmapslocsharing'
```

**Comment by shr00mie** [comment]
if your install is under /srv, then that looks less like an ubuntu install and more like a [manual hass raspberry pi install under a venv](https://www.home-assistant.io/docs/installation/raspberry-pi/), which i have yet to get around to supporting.

go read the docs for your install method or explore your device and figure out where the respective custom_components and deps directories are for your install method and adjust accordingly.

I'll probably get around to this at a later date, but my plate is a bit full with another project at the moment. If/when you confirm your install method, OS, and custom_component and deps directories, i could probably include a script for that as well for anyone in a similar situation as yourself.

**Comment by njf2125** [comment]
I think it was as simple as moving the gmapslocsharing folder that was pulled down from here into /srv/homeassistant/lib/python3.6/site-packages/

Things appear to be working now.  I'm not sure how difficult or complex this would be as far as scripting though.

Oddly enough, even though it appears to be working, I'm seeing this when HA starts:
2019-06-03 12:15:05 ERROR (SyncWorker_1) [gmapslocsharing] Login either not present or not valid.

**Comment by shr00mie** [comment]
If you're on the HA discord, drop me a PM there and I'll see if I can figure out what's going on with your login.

Same username.
